### ISSUE TITLE
On frame reload, frame is blank in editor, but not in timeline

### ISSUE THREAD

**Issue by IBwWG** [zrispo/wick#479] opened 2017-03-21 10:50 UTC
![wickeditor bug 1](https://cloud.githubusercontent.com/assets/16719964/24144204/be8db51c-0e2c-11e7-95aa-29d0d3f5420f.png)

1. Draw something
1. Click frame 2
1. Click frame 1--editor is blank
1. Draw more stuff--editor shows only new stuff, timeline shows combined (see above screenshot)
1. Browser page refresh--editor is blank again, timeline shows same combined as above

Chromium Version 56.0.2924.76 Built on Ubuntu , running on LinuxMint 18.1 (64-bit)

**Comment by zrispo** [comment] 2017-03-21 16:00
Can't reproduce on my machine (macOS) -- looking into this further on linux

**Comment by zrispo** [comment] 2017-04-26 06:17
Fixed in experimental branch

**Closed by zrispo** 2017-04-26 06:17 UTC
Labels: Bug
